import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  // Must match the BrowserRouter 'basename' in 'main.jsx'
  base: '/',
  plugins: [react()],
  publicDir: 'public',
  build: {
    // Disabled for production: avoids shipping .map files and exposing source.
    // The sitemap is generated by the `sitemap` npm script in the build step.
    sourcemap: false,
  },
  css: {
    devSourcemap: true, // Still useful for development
  },
});
